config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  namespace :admin do
    resources :schedules
    resources :addresses
    resources :sells
    resources :campaigns
    resources :discounts
    resources :services
    resources :products
    resources :suppliers
    resources :clients
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/address.rb
class Address < ApplicationRecord
  include Fae::BaseModelConcern
  belongs_to :client

  def fae_display_field
    name
  end

  def self.for_fae_index
    order(:id)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, presence: true
  validates :body, presence: true

  has_many :campaign_clients
  has_many :clients, through: :campaign_clients, dependent: :destroy

  after_save :schedule_emails

  def fae_display_field
    title
  end

  def schedule_emails
    Client.all.each do |client|
      CampaignClient.create(campaign: self, client: client)
      CampaingJob.perform_later client, self.title, self.body
    end
  end
end

app/models/campaign_client.rb
class CampaignClient < ApplicationRecord
  belongs_to :campaign
  belongs_to :client
end

app/models/client.rb
class Client < ApplicationRecord
  include Fae::BaseModelConcern

  has_many :campaign_clients
  has_many :campaigns, through: :campaign_clients, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :name, presence: true
  validates :phone, presence: true
  validates :email,
    uniqueness: true,
    presence: true,
    format: {
      with: Fae.validation_helpers.email_regex,
      message: 'You need use a valid and unique email'
    }

  def fae_display_field
    name
  end

end

app/models/discount.rb
class Discount < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, uniqueness: true, presence: true
  validates :value, uniqueness: true, presence: true
  validates :discount_type, presence: true

  # enum type: {money: 0, percentual: 1}

  def fae_display_field
    title
  end

end

app/models/product.rb
class Product < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_image :hero_image

  validates :title, uniqueness: true, presence: true
  validates :price, presence: true
  
  def fae_display_field
    title
  end

  belongs_to :supplier
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  include Fae::BaseModelConcern
  validates :date, presence: true
  validates :time, presence: true
  validates :service, presence: true
  validates :client, presence: true

  def fae_display_field
    date
  end

  belongs_to :service
  belongs_to :client

  after_save :schedule_emails

  def fae_display_field
    date
  end

  def self.for_fae_index
    order(:id)
  end

  def schedule_emails
    ScheduleJob.perform_later self
  end

end

app/models/sell.rb
class Sell < ApplicationRecord
  include Fae::BaseModelConcern
  enum status: { finished: 0, canceled: 1 }

  validates :client, presence: true

  belongs_to :discount
  belongs_to :client

  has_many :sell_products
  has_many :products, through: :sell_products, dependent: :destroy

  has_many :sell_services
  has_many :services, through: :sell_services, dependent: :destroy

  before_save :set_total

  def fae_display_field
    id
  end

  def self.for_fae_index
    order(:id)
  end

  private

  def set_total
    total = 0
    self.products.each {|p| total += p.price }
    self.services.each {|s| total += s.price }
    total = get_total_with_discount(total) if self.discount.present?
    total = (total >= 0)? total : 0
    self.total = total
  end

  def get_total_with_discount(total)
    return total_with_discount_in_money(total) if is_discount_with_money?
    return total_with_discount_in_percentagem(total)
  end

  def is_discount_with_money?
    self.discount.discount_type == 0
  end

  def total_with_discount_in_money(total)
    total - self.discount.value
  end

  def total_with_discount_in_percentagem(total)
    total * (1 - (self.discount.value/100))
  end
end

app/models/sell_product.rb
class SellProduct < ApplicationRecord
  belongs_to :product
  belongs_to :sell
end

app/models/sell_service.rb
class SellService < ApplicationRecord
  belongs_to :service
  belongs_to :sell
end

app/models/service.rb
class Service < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_image :hero_image

  validates :title, uniqueness: true, presence: true
  validates :price, presence: true

  def fae_display_field
    title
  end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  include Fae::BaseModelConcern

  validates :name, uniqueness: true, presence: true
  validates :phone, presence: true
  validates :email,
    uniqueness: true,
    presence: true,
    format: {
      with: Fae.validation_helpers.email_regex,
      message: 'You need use a valid and unique email'
    }
    
  def fae_display_field
    name
  end

end

app/controllers/admin/addresses_controller.rb
module Admin
  class AddressesController < Fae::BaseController

  end
end

app/controllers/admin/campaigns_controller.rb
module Admin
  class CampaignsController < Fae::BaseController

  end
end

app/controllers/admin/clients_controller.rb
module Admin
  class ClientsController < Fae::BaseController

  end
end

app/controllers/admin/discounts_controller.rb
module Admin
  class DiscountsController < Fae::BaseController

  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Fae::BaseController

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end

  end
end

app/controllers/admin/sells_controller.rb
module Admin
  class SellsController < Fae::BaseController
    before_action :adjust_enum, only: [:create, :ipdate]

    def adjust_enum
      params[:sell][:status] = params[:sell][:status].to_i
    end
  end
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < Fae::BaseController

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/campaigns/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :title
    = fae_input f, :body

app/views/admin/campaigns/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = item.title
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/clients/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name
    = fae_input f, :email
    = fae_input f, :observations
    = fae_input f, :phone

app/views/admin/clients/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize, csv: true

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th Email
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_client_path(item)
            td = item.email
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/discounts/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :title
    = fae_pulldown f, :discount_type, collection: {money: 0, percent: 1}
    = fae_prefix f, :value, prefix: '$', placeholder: '50.00'

app/views/admin/discounts/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th Type
        th Value
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_discount_path(item)
            td = ['money','percentual'][item.discount_type]
            td = item.value
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/products/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :title
    = fae_input f, :description
    = fae_prefix f, :price, prefix: '$', placeholder: '50.00'
    = fae_input f, :observations

    = fae_association f, :supplier

    = fae_image_form f, :hero_image

app/views/admin/products/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th Price
        th Supplier
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_product_path(item)
            td = item.price
            td = (item.supplier)? item.supplier.name : ''
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/sells/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_association f, :products
    = fae_association f, :services
    = fae_association f, :discount
    = fae_association f, :client
    = fae_datepicker f,  :date

    = fae_input f, :observations
    = fae_pulldown f, :status, size: 'long', collection: { finished: 0, canceled: 1 }, selected: 0

app/views/admin/sells/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize, csv: true

main.content
  table.js-sort-column
    thead
      tr
        th Id
        th Date
        th Client
        th Total
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_sell_path(item)
            td = item.date
            td = item.client.name
            td = item.total
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/services/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :title
    = fae_input f, :description
    = fae_prefix f, :price, prefix: '$', placeholder: '50.00'
    = fae_input f, :observations


    = fae_image_form f, :hero_image

app/views/admin/services/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th Price
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_service_path(item)
            td = item.price
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found